name: weekly-biblical-encouragement
summary: weekly-biblical-encouragement
version: 1.1.1
description: |
  This app’s mission is to encourage the viewer to draw closer 
  to God through weekly reading, inspirational verses, songs, Images and messages
confinement: classic
base: core18

parts:
  weekly-biblical-encouragement:
    plugin: nodejs
    source: https://github.com/casmedlin/wbelinux.git

apps:
  weekly-biblical-encouragement:
    command: weekly-biblical-encouragement
