 name: weeklybiblicalencouragementdirectories:
 description: This app’s mission is to encourage the viewer to draw closer to God through weekly reading, inspirational verses, songs, Images and messages
 directorie:  
  output: dist
  buildResources: build
electronVersion: 11.2.0
